name: quiz_bet
description: a quiz beting game application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #FOR UI
  cupertino_icons: ^1.0.2
  flutter_advanced_drawer: ^1.3.3
  sizer: ^2.0.15
  lottie: ^2.2.0
  scaled_list: ^2.0.0
  expandable_page_view: ^1.0.17
  page_view_indicators: ^2.0.0
  another_xlider: ^1.1.2
  bouncing_button: ^0.0.1+2
  appinio_swiper: ^1.1.1
  animated_text_kit: ^4.2.2
  pin_code_fields: ^7.4.0
  form_validator: ^2.1.1
  glassmorphism_ui: ^0.3.0
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  awesome_snackbar_content: ^0.1.0
  animated_snack_bar: ^0.3.0
  font_awesome_flutter:
    path: ../font_awesome_flutter/

  #FOR TIME MANAGEMENT(TIMER AND ALARM)
  timer_controller: ^0.1.0

  #FOR AUDIO
  flutter_beep: ^1.0.0

  #FOR DISPLAYING QR CODE
  pretty_qr_code: ^2.0.3

  #FOR NETWORK
  hasura_connect: ^4.0.0+4

  #FOR STATE MANAGEMENT
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1

  #FOR LOGGING
  logger: ^1.1.0

  #FOR STORAGE
  hive: ^2.2.3



dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/logos/
    - assets/lottie/
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito_light.ttf
          weight: 300
        - asset: assets/fonts/nunito_regular.ttf
          weight: 400
        - asset: assets/fonts/nunito_regular.ttf
          weight: 500
        - asset: assets/fonts/nunito_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/nunito_bold.ttf
          weight: 700


  uses-material-design: true
